name: "Build Armbian"
on:
  [push]
jobs:
  build-armbian:
    runs-on: ubuntu-latest
    steps:
      - uses: armbian/build@main
        with:
          armbian_token:     "${{ secrets.GITHUB_TOKEN }}"  # GitHub token
          armbian_release:   "jammy"                        # userspace
          armbian_target:    "build"                        # build=image, kernel=kernel
          armbian_kernel_branch:    "edge"
          armbian_ui:        "server"
          armbian_board:     "firefly-rk3399"                   # build target
      - name: Upload file
        uses: actions/upload-artifact@v4
        with:
          name: armbian
          path: build/output/images
