name: "Build Armbian"
on:
  workflow_dispatch:
jobs:
  build-armbian:
    runs-on: ubuntu-latest
    steps:
      - uses: armbian/build@main
        with:
          armbian_token:     "${{ secrets.GITHUB_TOKEN }}"  # GitHub token
          armbian_release:   "jammy"                        # userspace
          armbian_target:    "build"                        # build=image, kernel=kernel
          armbian_kernel_branch:    "edge"
          armbian_ui:        "server"
          armbian_board:     "firefly-rk3399"                   # build target
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}/output/images
